### ISSUE TITLE
Asking for help regarding the error produced at the code CropPhenology

### ISSUE THREAD

**Issue by prasen1985** [SofanitAraya/CropPhenology#1]
Dear Sofanit,
Thanks for developing such a code in R for handling the time series MODIS data. I am working on the crop phenology of lower Gangetic basin. I have tried with a raster time series stack. It looks like following.
```
> ndvimap
class       : RasterBrick 
dimensions  : 29, 24, 696, 360  (nrow, ncol, ncell, nlayers)
resolution  : 0.08331404, 0.08329475  (x, y)
extent      : -152.9646, -150.965, 66.30262, 68.71817  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 
data source : in memory
names       : X1982.01.01, X1982.02.01, X1982.03.01, X1982.04.01, X1982.05.01, X1982.06.01, X1982.07.01, X1982.08.01, X1982.09.01, X1982.10.01, X1982.11.01, X1982.12.01, X1983.01.01, X1983.02.01, X1983.03.01, ... 
min values  :       0.000,       0.000,       0.000,       0.000,       0.130,       0.350,       0.557,       0.537,       0.419,       0.074,       0.000,       0.000,       0.000,       0.000,       0.000, ... 
max values  :       0.266,       0.262,       0.293,       0.834,       0.666,       0.900,       0.998,       0.971,       0.832,       0.953,       0.704,       0.345,       0.262,       0.262,       0.306, ... 
Date        : 1982-01-16, 2011-12-16 (min, max)

```
However, the PhenoPlot command yield the following error
```
> pheno <- PhenoPlot(ndvimap)
Error in .local(x, ...) : invalid layer names

```
And the PhenoMetrics command yields the following error
```
> pheno <- PhenoMetrics(ndvimap)
[1] "Shapefiles is loaded correctly"
[1] "sp is loaded correctly"
[1] "sf is loaded correctly"
[1] "maptools is loaded correctly"
[1] "rgdal is loaded correctly"
[1] "xlsx is loaded correctly"
[1] "rgeos is loaded correctly"
[1] "raster is loaded correctly"
[1] "The default value, 20%, will be applied"
[1] "Unsmoothed curve will be used"
Error in dimnames(x) <- list(n) : 'dimnames' applied to non-array

```
Can you please help me to fix the error. 

Regards,

Prasenjit Acharya
Department of Geography and Environment Management
Vidyasagar University
Midnapore - 721102, IND

**Comment by SofanitAraya** [comment]
Dear Dr. Prasenjit Acharya,

Thank you very much for your email. It helps to make our package more user-friendly and useful. 
It is appreciated!

At the moment, CropPhenology takes RasterStack object (not a RasterStackTS). We are working on  adjusting that. Here is the screen capture of similar example I run in my side:

> ExampleStack #RasterStack object
class       : RasterStack 
dimensions  : 92, 65, 5980, 23  (nrow, ncol, ncell, nlayers)
resolution  : 231.6564, 231.6564  (x, y)
extent      : 904922.6, 919980.2, 1967133, 1988445  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=lcc +lat_1=-28 +lat_2=-36 +lat_0=-32 +lon_0=135 +x_0=1000000 +y_0=2000000 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
names       : MOD13Q1.A//2691703561, MOD13Q1.A//3570252331, MOD13Q1.A//2711637541, MOD13Q1.A//0010330481, MOD13Q1.A//0050802191, MOD13Q1.A//2771358211, MOD13Q1.A//0162254401, MOD13Q1.A//2821629341, MOD13Q1.A//0252013091, MOD13Q1.A//0621648391, MOD13Q1.A//0350454171, MOD13Q1.A//1660608231, MOD13Q1.A//0392035341, MOD13Q1.A//2230314201, MOD13Q1.A//0490927281, ... 
> ext <- as(extent(910000, 915000, 1975000,  1980000), 'SpatialPolygons')
> proj4string(ext) <- crs(ExampleStack)

> PhenoStack=CropPhenology::PhenoMetrics(ExampleStack, ext)
[1] "Shapefiles is loaded correctly"
[1] "sp is loaded correctly"
[1] "sf is loaded correctly"
[1] "maptools is loaded correctly"
[1] "rgdal is loaded correctly"
[1] "xlsx is loaded correctly"
[1] "rgeos is loaded correctly"
[1] "raster is loaded correctly"
[1] "The default value, 20%, will be applied"
[1] "Unsmoothed curve will be used"
> PhenoStack
class       : RasterStack 
dimensions  : 22, 22, 484, 15  (nrow, ncol, ncell, nlayers)
resolution  : 231.6564, 231.6564  (x, y)
extent      : 910019, 915115.5, 1975009, 1980106  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=lcc +lat_1=-28 +lat_2=-36 +lat_0=-32 +lon_0=135 +x_0=1000000 +y_0=2000000 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
names       : Onset_Value,  Onset_Time, Offset_Value, Offset_Time,   Max_Value,    Max_Time,      TINDVI, TINDVIBeforeMax, TINDVIAfterMax,   Asymmetry, GreenUpSlope, BrownDownSlope,    LengthGS,  BeforeMaxT,   AfterMaxT 
min values  :  0.15180001,  3.00000000,   0.14929999, 19.00000000,  0.41839999,  9.00000000,  3.78010002,      1.10029999,     1.08265000, -3.82604993,   0.02118462,     0.01581000, 10.00000000,  4.00000000,  2.00000000 
max values  :   0.3776000,  10.0000000,    0.3605000,  23.0000000,   0.8058000,  18.0000000,   7.5073000,       5.1502000,      5.1930999,   3.4870500,    0.1393750,      0.1683333,  20.0000000,  13.0000000,  11.0000000 
 
I hope this helps,

Please feel free to contact me if you have any question or comments, anytime!

Thanks again!

Kind Regards

--------------------------------------------
Sofanit Araya (PhD) 
Spatial Information Group (SIG)| School of Biological Sciences
The University of Adelaide| Oliphant Building, Rm 315 | Adelaide SA 5005
sofanitgirma.araya@adelaide.edu.au
https://researchers.adelaide.edu.au/profile/sofanitgirma.araya
